/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  Achats: () => import('#controllers/achats_controller'),
  Auth: () => import('#controllers/auth_controller'),
  Caisse: () => import('#controllers/caisse_controller'),
  Categories: () => import('#controllers/categories_controller'),
  Clients: () => import('#controllers/clients_controller'),
  DepenseCategories: () => import('#controllers/depense_categories_controller'),
  Depenses: () => import('#controllers/depenses_controller'),
  Fournisseurs: () => import('#controllers/fournisseurs_controller'),
  PointsDeVente: () => import('#controllers/points_de_vente_controller'),
  Produits: () => import('#controllers/produits_controller'),
  Rapports: () => import('#controllers/rapports_controller'),
  Reglements: () => import('#controllers/reglements_controller'),
  Stock: () => import('#controllers/stock_controller'),
  TvaGroupes: () => import('#controllers/tva_groupes_controller'),
  Users: () => import('#controllers/users_controller'),
  Ventes: () => import('#controllers/ventes_controller'),
}
