import '@adonisjs/core/types/http'

type ParamValue = string | number | bigint | boolean

export type ScannedRoutes = {
  ALL: {
    'auth.login': { paramsTuple?: []; params?: {} }
    'auth.logout': { paramsTuple?: []; params?: {} }
    'auth.me': { paramsTuple?: []; params?: {} }
    'auth.change_password': { paramsTuple?: []; params?: {} }
    'points_de_vente.search': { paramsTuple?: []; params?: {} }
    'points_de_vente.show': { paramsTuple?: []; params?: {} }
    'points_de_vente.create': { paramsTuple?: []; params?: {} }
    'points_de_vente.update': { paramsTuple?: []; params?: {} }
    'points_de_vente.deactivate': { paramsTuple?: []; params?: {} }
    'users.search': { paramsTuple?: []; params?: {} }
    'users.show': { paramsTuple?: []; params?: {} }
    'users.create': { paramsTuple?: []; params?: {} }
    'users.update': { paramsTuple?: []; params?: {} }
    'users.deactivate': { paramsTuple?: []; params?: {} }
    'users.permissions_catalog': { paramsTuple?: []; params?: {} }
    'users.permissions_show': { paramsTuple?: []; params?: {} }
    'users.permissions_update': { paramsTuple?: []; params?: {} }
    'admin.tva_groupes.search': { paramsTuple?: []; params?: {} }
    'admin.tva_groupes.show': { paramsTuple?: []; params?: {} }
    'admin.tva_groupes.create': { paramsTuple?: []; params?: {} }
    'admin.tva_groupes.update': { paramsTuple?: []; params?: {} }
    'admin.tva_groupes.deactivate': { paramsTuple?: []; params?: {} }
    'admin.categories.search': { paramsTuple?: []; params?: {} }
    'admin.categories.show': { paramsTuple?: []; params?: {} }
    'admin.categories.create': { paramsTuple?: []; params?: {} }
    'admin.categories.update': { paramsTuple?: []; params?: {} }
    'admin.categories.delete': { paramsTuple?: []; params?: {} }
    'admin.depense_categories.search': { paramsTuple?: []; params?: {} }
    'admin.depense_categories.show': { paramsTuple?: []; params?: {} }
    'admin.depense_categories.create': { paramsTuple?: []; params?: {} }
    'admin.depense_categories.update': { paramsTuple?: []; params?: {} }
    'admin.depense_categories.delete': { paramsTuple?: []; params?: {} }
    'clients.clients.search': { paramsTuple?: []; params?: {} }
    'clients.clients.show': { paramsTuple?: []; params?: {} }
    'clients.clients.create': { paramsTuple?: []; params?: {} }
    'clients.clients.update': { paramsTuple?: []; params?: {} }
    'clients.clients.deactivate': { paramsTuple?: []; params?: {} }
    'clients.clients.ventes': { paramsTuple?: []; params?: {} }
    'clients.clients.solde': { paramsTuple?: []; params?: {} }
    'fournisseurs.fournisseurs.search': { paramsTuple?: []; params?: {} }
    'fournisseurs.fournisseurs.show': { paramsTuple?: []; params?: {} }
    'fournisseurs.fournisseurs.create': { paramsTuple?: []; params?: {} }
    'fournisseurs.fournisseurs.update': { paramsTuple?: []; params?: {} }
    'fournisseurs.fournisseurs.deactivate': { paramsTuple?: []; params?: {} }
    'fournisseurs.fournisseurs.achats': { paramsTuple?: []; params?: {} }
    'categories.categories.search': { paramsTuple?: []; params?: {} }
    'categories.categories.show': { paramsTuple?: []; params?: {} }
    'categories.categories.create': { paramsTuple?: []; params?: {} }
    'categories.categories.update': { paramsTuple?: []; params?: {} }
    'categories.categories.delete': { paramsTuple?: []; params?: {} }
    'tva_groupes.index': { paramsTuple?: []; params?: {} }
    'tva_groupes.show': { paramsTuple?: []; params?: {} }
    'produits.produits.search': { paramsTuple?: []; params?: {} }
    'produits.produits.show': { paramsTuple?: []; params?: {} }
    'produits.produits.create': { paramsTuple?: []; params?: {} }
    'produits.produits.update': { paramsTuple?: []; params?: {} }
    'produits.produits.deactivate': { paramsTuple?: []; params?: {} }
    'produits.produits.alertes': { paramsTuple?: []; params?: {} }
    'produits.produits.ajustement': { paramsTuple?: []; params?: {} }
    'produits.produits.calcul_prix': { paramsTuple?: []; params?: {} }
    'ventes.search': { paramsTuple?: []; params?: {} }
    'ventes.get_by_criteria': { paramsTuple?: []; params?: {} }
    'ventes.show': { paramsTuple?: []; params?: {} }
    'ventes.ligne_info': { paramsTuple?: []; params?: {} }
    'ventes.create': { paramsTuple?: []; params?: {} }
    'ventes.update': { paramsTuple?: []; params?: {} }
    'ventes.annuler': { paramsTuple?: []; params?: {} }
    'ventes.convertir_facture': { paramsTuple?: []; params?: {} }
    'ventes.valider': { paramsTuple?: []; params?: {} }
    'ventes.delete': { paramsTuple?: []; params?: {} }
    'ventes.retour': { paramsTuple?: []; params?: {} }
    'ventes.paiement': { paramsTuple?: []; params?: {} }
    'ventes.paiements_search': { paramsTuple?: []; params?: {} }
    'ventes.document': { paramsTuple?: []; params?: {} }
    'ventes.imprimer': { paramsTuple?: []; params?: {} }
    'ventes.lock': { paramsTuple?: []; params?: {} }
    'ventes.lock_renew': { paramsTuple?: []; params?: {} }
    'ventes.unlock': { paramsTuple?: []; params?: {} }
    'reglements.client.create': { paramsTuple?: []; params?: {} }
    'reglements.client.search': { paramsTuple?: []; params?: {} }
    'reglements.client.show': { paramsTuple?: []; params?: {} }
    'reglements.fournisseur.create': { paramsTuple?: []; params?: {} }
    'reglements.fournisseur.search': { paramsTuple?: []; params?: {} }
    'reglements.fournisseur.show': { paramsTuple?: []; params?: {} }
    'achats.search': { paramsTuple?: []; params?: {} }
    'achats.get_by_criteria': { paramsTuple?: []; params?: {} }
    'achats.show': { paramsTuple?: []; params?: {} }
    'achats.ligne_info': { paramsTuple?: []; params?: {} }
    'achats.create': { paramsTuple?: []; params?: {} }
    'achats.update': { paramsTuple?: []; params?: {} }
    'achats.annuler': { paramsTuple?: []; params?: {} }
    'achats.recevoir': { paramsTuple?: []; params?: {} }
    'achats.retour': { paramsTuple?: []; params?: {} }
    'achats.paiement': { paramsTuple?: []; params?: {} }
    'caisse.solde': { paramsTuple?: []; params?: {} }
    'caisse.mouvements.search': { paramsTuple?: []; params?: {} }
    'caisse.get_by_criteria': { paramsTuple?: []; params?: {} }
    'caisse.mouvements.show': { paramsTuple?: []; params?: {} }
    'caisse.ouverture': { paramsTuple?: []; params?: {} }
    'caisse.fermeture': { paramsTuple?: []; params?: {} }
    'caisse.session': { paramsTuple?: []; params?: {} }
    'caisse.sessions.search': { paramsTuple?: []; params?: {} }
    'caisse.sessions.get_by_criteria': { paramsTuple?: []; params?: {} }
    'caisse.sessions.show': { paramsTuple?: []; params?: {} }
    'depense_categories.index': { paramsTuple?: []; params?: {} }
    'depenses.search': { paramsTuple?: []; params?: {} }
    'depenses.show': { paramsTuple?: []; params?: {} }
    'depenses.create': { paramsTuple?: []; params?: {} }
    'depenses.update': { paramsTuple?: []; params?: {} }
    'depenses.delete': { paramsTuple?: []; params?: {} }
    'stock.search': { paramsTuple?: []; params?: {} }
    'stock.mouvements.search': { paramsTuple?: []; params?: {} }
    'stock.valorisation': { paramsTuple?: []; params?: {} }
    'stock.alertes': { paramsTuple?: []; params?: {} }
    'rapports.caisse': { paramsTuple?: []; params?: {} }
    'rapports.stock_actuel': { paramsTuple?: []; params?: {} }
    'rapports.valeur_stock': { paramsTuple?: []; params?: {} }
    'rapports.balance_clients': { paramsTuple?: []; params?: {} }
    'rapports.releve_client': { paramsTuple?: []; params?: {} }
    'rapports.depenses': { paramsTuple?: []; params?: {} }
    'rapports.chiffre_affaires': { paramsTuple?: []; params?: {} }
    'rapports.balance_fournisseurs': { paramsTuple?: []; params?: {} }
    'rapports.releve_fournisseur': { paramsTuple?: []; params?: {} }
    'rapports.reglement_clients': { paramsTuple?: []; params?: {} }
    'rapports.reglement_fournisseurs': { paramsTuple?: []; params?: {} }
  }
  GET: {
    'auth.me': { paramsTuple?: []; params?: {} }
    'tva_groupes.index': { paramsTuple?: []; params?: {} }
    'caisse.solde': { paramsTuple?: []; params?: {} }
    'depense_categories.index': { paramsTuple?: []; params?: {} }
    'stock.valorisation': { paramsTuple?: []; params?: {} }
  }
  HEAD: {
    'auth.me': { paramsTuple?: []; params?: {} }
    'tva_groupes.index': { paramsTuple?: []; params?: {} }
    'caisse.solde': { paramsTuple?: []; params?: {} }
    'depense_categories.index': { paramsTuple?: []; params?: {} }
    'stock.valorisation': { paramsTuple?: []; params?: {} }
  }
  POST: {
    'auth.login': { paramsTuple?: []; params?: {} }
    'auth.logout': { paramsTuple?: []; params?: {} }
    'auth.change_password': { paramsTuple?: []; params?: {} }
    'points_de_vente.search': { paramsTuple?: []; params?: {} }
    'points_de_vente.show': { paramsTuple?: []; params?: {} }
    'points_de_vente.create': { paramsTuple?: []; params?: {} }
    'points_de_vente.update': { paramsTuple?: []; params?: {} }
    'points_de_vente.deactivate': { paramsTuple?: []; params?: {} }
    'users.search': { paramsTuple?: []; params?: {} }
    'users.show': { paramsTuple?: []; params?: {} }
    'users.create': { paramsTuple?: []; params?: {} }
    'users.update': { paramsTuple?: []; params?: {} }
    'users.deactivate': { paramsTuple?: []; params?: {} }
    'users.permissions_catalog': { paramsTuple?: []; params?: {} }
    'users.permissions_show': { paramsTuple?: []; params?: {} }
    'users.permissions_update': { paramsTuple?: []; params?: {} }
    'admin.tva_groupes.search': { paramsTuple?: []; params?: {} }
    'admin.tva_groupes.show': { paramsTuple?: []; params?: {} }
    'admin.tva_groupes.create': { paramsTuple?: []; params?: {} }
    'admin.tva_groupes.update': { paramsTuple?: []; params?: {} }
    'admin.tva_groupes.deactivate': { paramsTuple?: []; params?: {} }
    'admin.categories.search': { paramsTuple?: []; params?: {} }
    'admin.categories.show': { paramsTuple?: []; params?: {} }
    'admin.categories.create': { paramsTuple?: []; params?: {} }
    'admin.categories.update': { paramsTuple?: []; params?: {} }
    'admin.categories.delete': { paramsTuple?: []; params?: {} }
    'admin.depense_categories.search': { paramsTuple?: []; params?: {} }
    'admin.depense_categories.show': { paramsTuple?: []; params?: {} }
    'admin.depense_categories.create': { paramsTuple?: []; params?: {} }
    'admin.depense_categories.update': { paramsTuple?: []; params?: {} }
    'admin.depense_categories.delete': { paramsTuple?: []; params?: {} }
    'clients.clients.search': { paramsTuple?: []; params?: {} }
    'clients.clients.show': { paramsTuple?: []; params?: {} }
    'clients.clients.create': { paramsTuple?: []; params?: {} }
    'clients.clients.update': { paramsTuple?: []; params?: {} }
    'clients.clients.deactivate': { paramsTuple?: []; params?: {} }
    'clients.clients.ventes': { paramsTuple?: []; params?: {} }
    'clients.clients.solde': { paramsTuple?: []; params?: {} }
    'fournisseurs.fournisseurs.search': { paramsTuple?: []; params?: {} }
    'fournisseurs.fournisseurs.show': { paramsTuple?: []; params?: {} }
    'fournisseurs.fournisseurs.create': { paramsTuple?: []; params?: {} }
    'fournisseurs.fournisseurs.update': { paramsTuple?: []; params?: {} }
    'fournisseurs.fournisseurs.deactivate': { paramsTuple?: []; params?: {} }
    'fournisseurs.fournisseurs.achats': { paramsTuple?: []; params?: {} }
    'categories.categories.search': { paramsTuple?: []; params?: {} }
    'categories.categories.show': { paramsTuple?: []; params?: {} }
    'categories.categories.create': { paramsTuple?: []; params?: {} }
    'categories.categories.update': { paramsTuple?: []; params?: {} }
    'categories.categories.delete': { paramsTuple?: []; params?: {} }
    'tva_groupes.show': { paramsTuple?: []; params?: {} }
    'produits.produits.search': { paramsTuple?: []; params?: {} }
    'produits.produits.show': { paramsTuple?: []; params?: {} }
    'produits.produits.create': { paramsTuple?: []; params?: {} }
    'produits.produits.update': { paramsTuple?: []; params?: {} }
    'produits.produits.deactivate': { paramsTuple?: []; params?: {} }
    'produits.produits.alertes': { paramsTuple?: []; params?: {} }
    'produits.produits.ajustement': { paramsTuple?: []; params?: {} }
    'produits.produits.calcul_prix': { paramsTuple?: []; params?: {} }
    'ventes.search': { paramsTuple?: []; params?: {} }
    'ventes.get_by_criteria': { paramsTuple?: []; params?: {} }
    'ventes.show': { paramsTuple?: []; params?: {} }
    'ventes.ligne_info': { paramsTuple?: []; params?: {} }
    'ventes.create': { paramsTuple?: []; params?: {} }
    'ventes.update': { paramsTuple?: []; params?: {} }
    'ventes.annuler': { paramsTuple?: []; params?: {} }
    'ventes.convertir_facture': { paramsTuple?: []; params?: {} }
    'ventes.valider': { paramsTuple?: []; params?: {} }
    'ventes.delete': { paramsTuple?: []; params?: {} }
    'ventes.retour': { paramsTuple?: []; params?: {} }
    'ventes.paiement': { paramsTuple?: []; params?: {} }
    'ventes.paiements_search': { paramsTuple?: []; params?: {} }
    'ventes.document': { paramsTuple?: []; params?: {} }
    'ventes.imprimer': { paramsTuple?: []; params?: {} }
    'ventes.lock': { paramsTuple?: []; params?: {} }
    'ventes.lock_renew': { paramsTuple?: []; params?: {} }
    'ventes.unlock': { paramsTuple?: []; params?: {} }
    'reglements.client.create': { paramsTuple?: []; params?: {} }
    'reglements.client.search': { paramsTuple?: []; params?: {} }
    'reglements.client.show': { paramsTuple?: []; params?: {} }
    'reglements.fournisseur.create': { paramsTuple?: []; params?: {} }
    'reglements.fournisseur.search': { paramsTuple?: []; params?: {} }
    'reglements.fournisseur.show': { paramsTuple?: []; params?: {} }
    'achats.search': { paramsTuple?: []; params?: {} }
    'achats.get_by_criteria': { paramsTuple?: []; params?: {} }
    'achats.show': { paramsTuple?: []; params?: {} }
    'achats.ligne_info': { paramsTuple?: []; params?: {} }
    'achats.create': { paramsTuple?: []; params?: {} }
    'achats.update': { paramsTuple?: []; params?: {} }
    'achats.annuler': { paramsTuple?: []; params?: {} }
    'achats.recevoir': { paramsTuple?: []; params?: {} }
    'achats.retour': { paramsTuple?: []; params?: {} }
    'achats.paiement': { paramsTuple?: []; params?: {} }
    'caisse.mouvements.search': { paramsTuple?: []; params?: {} }
    'caisse.get_by_criteria': { paramsTuple?: []; params?: {} }
    'caisse.mouvements.show': { paramsTuple?: []; params?: {} }
    'caisse.ouverture': { paramsTuple?: []; params?: {} }
    'caisse.fermeture': { paramsTuple?: []; params?: {} }
    'caisse.session': { paramsTuple?: []; params?: {} }
    'caisse.sessions.search': { paramsTuple?: []; params?: {} }
    'caisse.sessions.get_by_criteria': { paramsTuple?: []; params?: {} }
    'caisse.sessions.show': { paramsTuple?: []; params?: {} }
    'depenses.search': { paramsTuple?: []; params?: {} }
    'depenses.show': { paramsTuple?: []; params?: {} }
    'depenses.create': { paramsTuple?: []; params?: {} }
    'depenses.update': { paramsTuple?: []; params?: {} }
    'depenses.delete': { paramsTuple?: []; params?: {} }
    'stock.search': { paramsTuple?: []; params?: {} }
    'stock.mouvements.search': { paramsTuple?: []; params?: {} }
    'stock.alertes': { paramsTuple?: []; params?: {} }
    'rapports.caisse': { paramsTuple?: []; params?: {} }
    'rapports.stock_actuel': { paramsTuple?: []; params?: {} }
    'rapports.valeur_stock': { paramsTuple?: []; params?: {} }
    'rapports.balance_clients': { paramsTuple?: []; params?: {} }
    'rapports.releve_client': { paramsTuple?: []; params?: {} }
    'rapports.depenses': { paramsTuple?: []; params?: {} }
    'rapports.chiffre_affaires': { paramsTuple?: []; params?: {} }
    'rapports.balance_fournisseurs': { paramsTuple?: []; params?: {} }
    'rapports.releve_fournisseur': { paramsTuple?: []; params?: {} }
    'rapports.reglement_clients': { paramsTuple?: []; params?: {} }
    'rapports.reglement_fournisseurs': { paramsTuple?: []; params?: {} }
  }
}
declare module '@adonisjs/core/types/http' {
  export interface RoutesList extends ScannedRoutes {}
}