/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from '@adonisjs/lucid/orm'
import { DateTime } from 'luxon'

export class AchatLigneSchema extends BaseModel {
  static $columns = ['achatId', 'createdAt', 'designation', 'frais', 'id', 'ligneOrigineId', 'modeAchat', 'montantHt', 'montantTtc', 'montantTva', 'prixUnitaireHt', 'produitId', 'quantite', 'quantiteRecue', 'quantiteRetournee', 'quantiteStock', 'tvaPct', 'updatedAt'] as const
  $columns = AchatLigneSchema.$columns
  @column()
  declare achatId: number
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare designation: string
  @column()
  declare frais: string
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare ligneOrigineId: number | null
  @column()
  declare modeAchat: string
  @column()
  declare montantHt: string
  @column()
  declare montantTtc: string
  @column()
  declare montantTva: string
  @column()
  declare prixUnitaireHt: string
  @column()
  declare produitId: number
  @column()
  declare quantite: string
  @column()
  declare quantiteRecue: string
  @column()
  declare quantiteRetournee: string
  @column()
  declare quantiteStock: string | null
  @column()
  declare tvaPct: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class AchatSchema extends BaseModel {
  static $columns = ['achatOrigineId', 'createdAt', 'dateAchat', 'dateReception', 'fournisseurId', 'id', 'montantPaye', 'notes', 'numero', 'pointDeVenteId', 'referenceFournisseur', 'remiseMontant', 'resteAPayer', 'sousTotal', 'statut', 'statutPaiement', 'totalTtc', 'tvaMontant', 'updatedAt', 'userId'] as const
  $columns = AchatSchema.$columns
  @column()
  declare achatOrigineId: number | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.date()
  declare dateAchat: DateTime
  @column.date()
  declare dateReception: DateTime | null
  @column()
  declare fournisseurId: number
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare montantPaye: string
  @column()
  declare notes: string | null
  @column()
  declare numero: string
  @column()
  declare pointDeVenteId: number
  @column()
  declare referenceFournisseur: string | null
  @column()
  declare remiseMontant: string
  @column()
  declare resteAPayer: string
  @column()
  declare sousTotal: string
  @column()
  declare statut: string
  @column()
  declare statutPaiement: string
  @column()
  declare totalTtc: string
  @column()
  declare tvaMontant: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: number
}

export class AuthAccessTokenSchema extends BaseModel {
  static $columns = ['abilities', 'createdAt', 'expiresAt', 'hash', 'id', 'lastUsedAt', 'name', 'tokenableId', 'type', 'updatedAt'] as const
  $columns = AuthAccessTokenSchema.$columns
  @column()
  declare abilities: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column.dateTime()
  declare expiresAt: DateTime | null
  @column()
  declare hash: string
  @column({ isPrimary: true })
  declare id: number
  @column.dateTime()
  declare lastUsedAt: DateTime | null
  @column()
  declare name: string | null
  @column()
  declare tokenableId: number
  @column()
  declare type: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class CaisseMouvementSchema extends BaseModel {
  static $columns = ['caisseId', 'caisseSessionId', 'createdAt', 'dateMouvement', 'id', 'libelle', 'montant', 'motif', 'notes', 'referenceId', 'referenceType', 'soldeApres', 'soldeAvant', 'type', 'userId'] as const
  $columns = CaisseMouvementSchema.$columns
  @column()
  declare caisseId: number
  @column()
  declare caisseSessionId: number | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime()
  declare dateMouvement: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare libelle: string
  @column()
  declare montant: string
  @column()
  declare motif: string
  @column()
  declare notes: string | null
  @column()
  declare referenceId: number | null
  @column()
  declare referenceType: string | null
  @column()
  declare soldeApres: string
  @column()
  declare soldeAvant: string
  @column()
  declare type: string
  @column()
  declare userId: number
}

export class CaisseSessionSchema extends BaseModel {
  static $columns = ['caisseId', 'createdAt', 'dateFermeture', 'dateOuverture', 'ecart', 'id', 'montantFermeture', 'montantOuverture', 'notesFermeture', 'notesOuverture', 'pointDeVenteId', 'soldeTheorique', 'statut', 'updatedAt', 'userFermetureId', 'userOuvertureId'] as const
  $columns = CaisseSessionSchema.$columns
  @column()
  declare caisseId: number
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime()
  declare dateFermeture: DateTime | null
  @column.dateTime()
  declare dateOuverture: DateTime
  @column()
  declare ecart: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare montantFermeture: string | null
  @column()
  declare montantOuverture: string
  @column()
  declare notesFermeture: string | null
  @column()
  declare notesOuverture: string | null
  @column()
  declare pointDeVenteId: number
  @column()
  declare soldeTheorique: string | null
  @column()
  declare statut: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userFermetureId: number | null
  @column()
  declare userOuvertureId: number
}

export class CaissSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'isActive', 'nom', 'pointDeVenteId', 'soldeActuel', 'updatedAt'] as const
  $columns = CaissSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare isActive: boolean
  @column()
  declare nom: string
  @column()
  declare pointDeVenteId: number
  @column()
  declare soldeActuel: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class CategorySchema extends BaseModel {
  static $columns = ['createdAt', 'description', 'id', 'nom', 'pointDeVenteId', 'updatedAt'] as const
  $columns = CategorySchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare description: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare nom: string
  @column()
  declare pointDeVenteId: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class ClientSchema extends BaseModel {
  static $columns = ['adresse', 'code', 'createdAt', 'creditLimit', 'email', 'id', 'isActive', 'nom', 'notes', 'pays', 'pointDeVenteId', 'solde', 'telephone', 'type', 'updatedAt', 'ville'] as const
  $columns = ClientSchema.$columns
  @column()
  declare adresse: string | null
  @column()
  declare code: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare creditLimit: string
  @column()
  declare email: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare isActive: boolean
  @column()
  declare nom: string
  @column()
  declare notes: string | null
  @column()
  declare pays: string
  @column()
  declare pointDeVenteId: number
  @column()
  declare solde: string
  @column()
  declare telephone: string | null
  @column()
  declare type: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare ville: string | null
}

export class DepenseCategorySchema extends BaseModel {
  static $columns = ['code', 'createdAt', 'id', 'isActive', 'libelle', 'updatedAt'] as const
  $columns = DepenseCategorySchema.$columns
  @column()
  declare code: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare isActive: boolean
  @column()
  declare libelle: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class DepenseSchema extends BaseModel {
  static $columns = ['caisseId', 'categorie', 'createdAt', 'dateDepense', 'id', 'libelle', 'montant', 'notes', 'pointDeVenteId', 'updatedAt', 'userId'] as const
  $columns = DepenseSchema.$columns
  @column()
  declare caisseId: number
  @column()
  declare categorie: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.date()
  declare dateDepense: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare libelle: string
  @column()
  declare montant: string
  @column()
  declare notes: string | null
  @column()
  declare pointDeVenteId: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: number
}

export class FournisseurSchema extends BaseModel {
  static $columns = ['adresse', 'code', 'contactNom', 'createdAt', 'email', 'id', 'isActive', 'nom', 'notes', 'pays', 'solde', 'telephone', 'updatedAt', 'ville'] as const
  $columns = FournisseurSchema.$columns
  @column()
  declare adresse: string | null
  @column()
  declare code: string
  @column()
  declare contactNom: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare email: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare isActive: boolean
  @column()
  declare nom: string
  @column()
  declare notes: string | null
  @column()
  declare pays: string | null
  @column()
  declare solde: string
  @column()
  declare telephone: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare ville: string | null
}

export class PaiementSchema extends BaseModel {
  static $columns = ['createdAt', 'datePaiement', 'id', 'modePaiement', 'montant', 'notes', 'referenceId', 'referencePaiement', 'type', 'updatedAt', 'userId'] as const
  $columns = PaiementSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.date()
  declare datePaiement: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare modePaiement: string
  @column()
  declare montant: string
  @column()
  declare notes: string | null
  @column()
  declare referenceId: number
  @column()
  declare referencePaiement: string | null
  @column()
  declare type: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: number
}

export class PointsDeVenteSchema extends BaseModel {
  static $columns = ['adresse', 'code', 'createdAt', 'id', 'isActive', 'nom', 'telephone', 'updatedAt', 'ville'] as const
  $columns = PointsDeVenteSchema.$columns
  @column()
  declare adresse: string | null
  @column()
  declare code: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare isActive: boolean
  @column()
  declare nom: string
  @column()
  declare telephone: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare ville: string | null
}

export class ProduitSchema extends BaseModel {
  static $columns = ['categorieId', 'code', 'contenance', 'createdAt', 'dernierPrixAchatHt', 'description', 'frais', 'id', 'isActive', 'nom', 'plancher', 'pointDeVenteId', 'prixAchatHt', 'prixAchatTtc', 'prixVenteHt', 'prixVenteTtc', 'stockActuel', 'stockMaximum', 'stockMinimum', 'tvaGroupeId', 'unite', 'uniteGros', 'updatedAt', 'venteAuDetail'] as const
  $columns = ProduitSchema.$columns
  @column()
  declare categorieId: number | null
  @column()
  declare code: string
  @column()
  declare contenance: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare dernierPrixAchatHt: string
  @column()
  declare description: string | null
  @column()
  declare frais: string
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare isActive: boolean
  @column()
  declare nom: string
  @column()
  declare plancher: string
  @column()
  declare pointDeVenteId: number
  @column()
  declare prixAchatHt: string
  @column()
  declare prixAchatTtc: string
  @column()
  declare prixVenteHt: string
  @column()
  declare prixVenteTtc: string
  @column()
  declare stockActuel: string
  @column()
  declare stockMaximum: string
  @column()
  declare stockMinimum: string
  @column()
  declare tvaGroupeId: number
  @column()
  declare unite: string
  @column()
  declare uniteGros: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare venteAuDetail: boolean
}

export class RateLimitSchema extends BaseModel {
  static $columns = ['expire', 'key', 'points'] as const
  $columns = RateLimitSchema.$columns
  @column()
  declare expire: bigint | number | null
  @column({ isPrimary: true })
  declare key: string
  @column()
  declare points: number
}

export class ReglementSchema extends BaseModel {
  static $columns = ['clientId', 'createdAt', 'dateReglement', 'fournisseurId', 'id', 'modePaiement', 'montant', 'notes', 'pointDeVenteId', 'referenceExterne', 'soldeApres', 'soldeAvant', 'type', 'updatedAt', 'userId'] as const
  $columns = ReglementSchema.$columns
  @column()
  declare clientId: number | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.date()
  declare dateReglement: DateTime
  @column()
  declare fournisseurId: number | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare modePaiement: string
  @column()
  declare montant: string
  @column()
  declare notes: string | null
  @column()
  declare pointDeVenteId: number
  @column()
  declare referenceExterne: string | null
  @column()
  declare soldeApres: string
  @column()
  declare soldeAvant: string
  @column()
  declare type: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: number
}

export class StockMouvementSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'motif', 'notes', 'produitId', 'quantite', 'referenceId', 'referenceType', 'stockApres', 'stockAvant', 'type', 'userId'] as const
  $columns = StockMouvementSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare motif: string
  @column()
  declare notes: string | null
  @column()
  declare produitId: number
  @column()
  declare quantite: string
  @column()
  declare referenceId: number | null
  @column()
  declare referenceType: string | null
  @column()
  declare stockApres: string
  @column()
  declare stockAvant: string
  @column()
  declare type: string
  @column()
  declare userId: number
}

export class TvaGroupeSchema extends BaseModel {
  static $columns = ['code', 'createdAt', 'id', 'isActive', 'libelle', 'taux', 'updatedAt'] as const
  $columns = TvaGroupeSchema.$columns
  @column()
  declare code: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare isActive: boolean
  @column()
  declare libelle: string
  @column()
  declare taux: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class UserSchema extends BaseModel {
  static $columns = ['createdAt', 'email', 'fullName', 'id', 'isActive', 'nom', 'password', 'permissions', 'pointDeVenteId', 'prenom', 'role', 'updatedAt'] as const
  $columns = UserSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare email: string
  @column()
  declare fullName: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare isActive: boolean
  @column()
  declare nom: string | null
  @column({ serializeAs: null })
  declare password: string
  @column()
  declare permissions: any | null
  @column()
  declare pointDeVenteId: number | null
  @column()
  declare prenom: string | null
  @column()
  declare role: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class VenteLigneSchema extends BaseModel {
  static $columns = ['createdAt', 'designation', 'id', 'ligneOrigineId', 'marge', 'modeVente', 'montantHt', 'montantTtc', 'montantTva', 'plancherLigne', 'prixUnitaire', 'produitId', 'quantite', 'quantiteRetournee', 'quantiteStock', 'remisePct', 'tvaPct', 'updatedAt', 'venteId'] as const
  $columns = VenteLigneSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare designation: string
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare ligneOrigineId: number | null
  @column()
  declare marge: string
  @column()
  declare modeVente: string
  @column()
  declare montantHt: string
  @column()
  declare montantTtc: string
  @column()
  declare montantTva: string
  @column()
  declare plancherLigne: string
  @column()
  declare prixUnitaire: string
  @column()
  declare produitId: number
  @column()
  declare quantite: string
  @column()
  declare quantiteRetournee: string
  @column()
  declare quantiteStock: string | null
  @column()
  declare remisePct: string
  @column()
  declare tvaPct: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare venteId: number
}

export class VenteSchema extends BaseModel {
  static $columns = ['bonSortieImpressionCount', 'clientId', 'createdAt', 'dateEcheance', 'dateVente', 'devisOrigineId', 'factureImpressionCount', 'factureOrigineId', 'id', 'lockExpiresAt', 'lockedAt', 'lockedByUserId', 'montantPaye', 'notes', 'numero', 'pointDeVenteId', 'remiseMontant', 'remisePct', 'resteAPayer', 'sousTotal', 'statut', 'statutPaiement', 'totalTtc', 'tvaMontant', 'updatedAt', 'userId'] as const
  $columns = VenteSchema.$columns
  @column()
  declare bonSortieImpressionCount: number
  @column()
  declare clientId: number
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.date()
  declare dateEcheance: DateTime | null
  @column.date()
  declare dateVente: DateTime
  @column()
  declare devisOrigineId: number | null
  @column()
  declare factureImpressionCount: number
  @column()
  declare factureOrigineId: number | null
  @column({ isPrimary: true })
  declare id: number
  @column.dateTime()
  declare lockExpiresAt: DateTime | null
  @column.dateTime()
  declare lockedAt: DateTime | null
  @column()
  declare lockedByUserId: number | null
  @column()
  declare montantPaye: string
  @column()
  declare notes: string | null
  @column()
  declare numero: string
  @column()
  declare pointDeVenteId: number
  @column()
  declare remiseMontant: string
  @column()
  declare remisePct: string
  @column()
  declare resteAPayer: string
  @column()
  declare sousTotal: string
  @column()
  declare statut: string
  @column()
  declare statutPaiement: string
  @column()
  declare totalTtc: string
  @column()
  declare tvaMontant: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: number
}
