/* eslint-disable prettier/prettier */
import type { AdonisEndpoint } from '@tuyau/core/types'
import type { Registry } from './schema.d.ts'
import type { ApiDefinition } from './tree.d.ts'

const placeholder: any = {}

const routes = {
  'auth.login': {
    methods: ["POST"],
    pattern: '/api/v1/auth/login',
    tokens: [{"old":"/api/v1/auth/login","type":0,"val":"api","end":""},{"old":"/api/v1/auth/login","type":0,"val":"v1","end":""},{"old":"/api/v1/auth/login","type":0,"val":"auth","end":""},{"old":"/api/v1/auth/login","type":0,"val":"login","end":""}],
    types: placeholder as Registry['auth.login']['types'],
  },
  'auth.logout': {
    methods: ["POST"],
    pattern: '/api/v1/auth/logout',
    tokens: [{"old":"/api/v1/auth/logout","type":0,"val":"api","end":""},{"old":"/api/v1/auth/logout","type":0,"val":"v1","end":""},{"old":"/api/v1/auth/logout","type":0,"val":"auth","end":""},{"old":"/api/v1/auth/logout","type":0,"val":"logout","end":""}],
    types: placeholder as Registry['auth.logout']['types'],
  },
  'auth.me': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/auth/me',
    tokens: [{"old":"/api/v1/auth/me","type":0,"val":"api","end":""},{"old":"/api/v1/auth/me","type":0,"val":"v1","end":""},{"old":"/api/v1/auth/me","type":0,"val":"auth","end":""},{"old":"/api/v1/auth/me","type":0,"val":"me","end":""}],
    types: placeholder as Registry['auth.me']['types'],
  },
  'auth.change_password': {
    methods: ["POST"],
    pattern: '/api/v1/auth/change-password',
    tokens: [{"old":"/api/v1/auth/change-password","type":0,"val":"api","end":""},{"old":"/api/v1/auth/change-password","type":0,"val":"v1","end":""},{"old":"/api/v1/auth/change-password","type":0,"val":"auth","end":""},{"old":"/api/v1/auth/change-password","type":0,"val":"change-password","end":""}],
    types: placeholder as Registry['auth.change_password']['types'],
  },
  'points_de_vente.search': {
    methods: ["POST"],
    pattern: '/api/v1/points-de-vente/search',
    tokens: [{"old":"/api/v1/points-de-vente/search","type":0,"val":"api","end":""},{"old":"/api/v1/points-de-vente/search","type":0,"val":"v1","end":""},{"old":"/api/v1/points-de-vente/search","type":0,"val":"points-de-vente","end":""},{"old":"/api/v1/points-de-vente/search","type":0,"val":"search","end":""}],
    types: placeholder as Registry['points_de_vente.search']['types'],
  },
  'points_de_vente.show': {
    methods: ["POST"],
    pattern: '/api/v1/points-de-vente/show',
    tokens: [{"old":"/api/v1/points-de-vente/show","type":0,"val":"api","end":""},{"old":"/api/v1/points-de-vente/show","type":0,"val":"v1","end":""},{"old":"/api/v1/points-de-vente/show","type":0,"val":"points-de-vente","end":""},{"old":"/api/v1/points-de-vente/show","type":0,"val":"show","end":""}],
    types: placeholder as Registry['points_de_vente.show']['types'],
  },
  'points_de_vente.create': {
    methods: ["POST"],
    pattern: '/api/v1/points-de-vente/create',
    tokens: [{"old":"/api/v1/points-de-vente/create","type":0,"val":"api","end":""},{"old":"/api/v1/points-de-vente/create","type":0,"val":"v1","end":""},{"old":"/api/v1/points-de-vente/create","type":0,"val":"points-de-vente","end":""},{"old":"/api/v1/points-de-vente/create","type":0,"val":"create","end":""}],
    types: placeholder as Registry['points_de_vente.create']['types'],
  },
  'points_de_vente.update': {
    methods: ["POST"],
    pattern: '/api/v1/points-de-vente/update',
    tokens: [{"old":"/api/v1/points-de-vente/update","type":0,"val":"api","end":""},{"old":"/api/v1/points-de-vente/update","type":0,"val":"v1","end":""},{"old":"/api/v1/points-de-vente/update","type":0,"val":"points-de-vente","end":""},{"old":"/api/v1/points-de-vente/update","type":0,"val":"update","end":""}],
    types: placeholder as Registry['points_de_vente.update']['types'],
  },
  'points_de_vente.deactivate': {
    methods: ["POST"],
    pattern: '/api/v1/points-de-vente/deactivate',
    tokens: [{"old":"/api/v1/points-de-vente/deactivate","type":0,"val":"api","end":""},{"old":"/api/v1/points-de-vente/deactivate","type":0,"val":"v1","end":""},{"old":"/api/v1/points-de-vente/deactivate","type":0,"val":"points-de-vente","end":""},{"old":"/api/v1/points-de-vente/deactivate","type":0,"val":"deactivate","end":""}],
    types: placeholder as Registry['points_de_vente.deactivate']['types'],
  },
  'users.search': {
    methods: ["POST"],
    pattern: '/api/v1/users/search',
    tokens: [{"old":"/api/v1/users/search","type":0,"val":"api","end":""},{"old":"/api/v1/users/search","type":0,"val":"v1","end":""},{"old":"/api/v1/users/search","type":0,"val":"users","end":""},{"old":"/api/v1/users/search","type":0,"val":"search","end":""}],
    types: placeholder as Registry['users.search']['types'],
  },
  'users.show': {
    methods: ["POST"],
    pattern: '/api/v1/users/show',
    tokens: [{"old":"/api/v1/users/show","type":0,"val":"api","end":""},{"old":"/api/v1/users/show","type":0,"val":"v1","end":""},{"old":"/api/v1/users/show","type":0,"val":"users","end":""},{"old":"/api/v1/users/show","type":0,"val":"show","end":""}],
    types: placeholder as Registry['users.show']['types'],
  },
  'users.create': {
    methods: ["POST"],
    pattern: '/api/v1/users/create',
    tokens: [{"old":"/api/v1/users/create","type":0,"val":"api","end":""},{"old":"/api/v1/users/create","type":0,"val":"v1","end":""},{"old":"/api/v1/users/create","type":0,"val":"users","end":""},{"old":"/api/v1/users/create","type":0,"val":"create","end":""}],
    types: placeholder as Registry['users.create']['types'],
  },
  'users.update': {
    methods: ["POST"],
    pattern: '/api/v1/users/update',
    tokens: [{"old":"/api/v1/users/update","type":0,"val":"api","end":""},{"old":"/api/v1/users/update","type":0,"val":"v1","end":""},{"old":"/api/v1/users/update","type":0,"val":"users","end":""},{"old":"/api/v1/users/update","type":0,"val":"update","end":""}],
    types: placeholder as Registry['users.update']['types'],
  },
  'users.deactivate': {
    methods: ["POST"],
    pattern: '/api/v1/users/deactivate',
    tokens: [{"old":"/api/v1/users/deactivate","type":0,"val":"api","end":""},{"old":"/api/v1/users/deactivate","type":0,"val":"v1","end":""},{"old":"/api/v1/users/deactivate","type":0,"val":"users","end":""},{"old":"/api/v1/users/deactivate","type":0,"val":"deactivate","end":""}],
    types: placeholder as Registry['users.deactivate']['types'],
  },
  'users.permissions_catalog': {
    methods: ["POST"],
    pattern: '/api/v1/users/permissions-catalog',
    tokens: [{"old":"/api/v1/users/permissions-catalog","type":0,"val":"api","end":""},{"old":"/api/v1/users/permissions-catalog","type":0,"val":"v1","end":""},{"old":"/api/v1/users/permissions-catalog","type":0,"val":"users","end":""},{"old":"/api/v1/users/permissions-catalog","type":0,"val":"permissions-catalog","end":""}],
    types: placeholder as Registry['users.permissions_catalog']['types'],
  },
  'users.permissions_show': {
    methods: ["POST"],
    pattern: '/api/v1/users/permissions/show',
    tokens: [{"old":"/api/v1/users/permissions/show","type":0,"val":"api","end":""},{"old":"/api/v1/users/permissions/show","type":0,"val":"v1","end":""},{"old":"/api/v1/users/permissions/show","type":0,"val":"users","end":""},{"old":"/api/v1/users/permissions/show","type":0,"val":"permissions","end":""},{"old":"/api/v1/users/permissions/show","type":0,"val":"show","end":""}],
    types: placeholder as Registry['users.permissions_show']['types'],
  },
  'users.permissions_update': {
    methods: ["POST"],
    pattern: '/api/v1/users/permissions/update',
    tokens: [{"old":"/api/v1/users/permissions/update","type":0,"val":"api","end":""},{"old":"/api/v1/users/permissions/update","type":0,"val":"v1","end":""},{"old":"/api/v1/users/permissions/update","type":0,"val":"users","end":""},{"old":"/api/v1/users/permissions/update","type":0,"val":"permissions","end":""},{"old":"/api/v1/users/permissions/update","type":0,"val":"update","end":""}],
    types: placeholder as Registry['users.permissions_update']['types'],
  },
  'admin.tva_groupes.search': {
    methods: ["POST"],
    pattern: '/api/v1/admin/tva-groupes/search',
    tokens: [{"old":"/api/v1/admin/tva-groupes/search","type":0,"val":"api","end":""},{"old":"/api/v1/admin/tva-groupes/search","type":0,"val":"v1","end":""},{"old":"/api/v1/admin/tva-groupes/search","type":0,"val":"admin","end":""},{"old":"/api/v1/admin/tva-groupes/search","type":0,"val":"tva-groupes","end":""},{"old":"/api/v1/admin/tva-groupes/search","type":0,"val":"search","end":""}],
    types: placeholder as Registry['admin.tva_groupes.search']['types'],
  },
  'admin.tva_groupes.show': {
    methods: ["POST"],
    pattern: '/api/v1/admin/tva-groupes/show',
    tokens: [{"old":"/api/v1/admin/tva-groupes/show","type":0,"val":"api","end":""},{"old":"/api/v1/admin/tva-groupes/show","type":0,"val":"v1","end":""},{"old":"/api/v1/admin/tva-groupes/show","type":0,"val":"admin","end":""},{"old":"/api/v1/admin/tva-groupes/show","type":0,"val":"tva-groupes","end":""},{"old":"/api/v1/admin/tva-groupes/show","type":0,"val":"show","end":""}],
    types: placeholder as Registry['admin.tva_groupes.show']['types'],
  },
  'admin.tva_groupes.create': {
    methods: ["POST"],
    pattern: '/api/v1/admin/tva-groupes/create',
    tokens: [{"old":"/api/v1/admin/tva-groupes/create","type":0,"val":"api","end":""},{"old":"/api/v1/admin/tva-groupes/create","type":0,"val":"v1","end":""},{"old":"/api/v1/admin/tva-groupes/create","type":0,"val":"admin","end":""},{"old":"/api/v1/admin/tva-groupes/create","type":0,"val":"tva-groupes","end":""},{"old":"/api/v1/admin/tva-groupes/create","type":0,"val":"create","end":""}],
    types: placeholder as Registry['admin.tva_groupes.create']['types'],
  },
  'admin.tva_groupes.update': {
    methods: ["POST"],
    pattern: '/api/v1/admin/tva-groupes/update',
    tokens: [{"old":"/api/v1/admin/tva-groupes/update","type":0,"val":"api","end":""},{"old":"/api/v1/admin/tva-groupes/update","type":0,"val":"v1","end":""},{"old":"/api/v1/admin/tva-groupes/update","type":0,"val":"admin","end":""},{"old":"/api/v1/admin/tva-groupes/update","type":0,"val":"tva-groupes","end":""},{"old":"/api/v1/admin/tva-groupes/update","type":0,"val":"update","end":""}],
    types: placeholder as Registry['admin.tva_groupes.update']['types'],
  },
  'admin.tva_groupes.deactivate': {
    methods: ["POST"],
    pattern: '/api/v1/admin/tva-groupes/deactivate',
    tokens: [{"old":"/api/v1/admin/tva-groupes/deactivate","type":0,"val":"api","end":""},{"old":"/api/v1/admin/tva-groupes/deactivate","type":0,"val":"v1","end":""},{"old":"/api/v1/admin/tva-groupes/deactivate","type":0,"val":"admin","end":""},{"old":"/api/v1/admin/tva-groupes/deactivate","type":0,"val":"tva-groupes","end":""},{"old":"/api/v1/admin/tva-groupes/deactivate","type":0,"val":"deactivate","end":""}],
    types: placeholder as Registry['admin.tva_groupes.deactivate']['types'],
  },
  'admin.categories.search': {
    methods: ["POST"],
    pattern: '/api/v1/admin/categories/search',
    tokens: [{"old":"/api/v1/admin/categories/search","type":0,"val":"api","end":""},{"old":"/api/v1/admin/categories/search","type":0,"val":"v1","end":""},{"old":"/api/v1/admin/categories/search","type":0,"val":"admin","end":""},{"old":"/api/v1/admin/categories/search","type":0,"val":"categories","end":""},{"old":"/api/v1/admin/categories/search","type":0,"val":"search","end":""}],
    types: placeholder as Registry['admin.categories.search']['types'],
  },
  'admin.categories.show': {
    methods: ["POST"],
    pattern: '/api/v1/admin/categories/show',
    tokens: [{"old":"/api/v1/admin/categories/show","type":0,"val":"api","end":""},{"old":"/api/v1/admin/categories/show","type":0,"val":"v1","end":""},{"old":"/api/v1/admin/categories/show","type":0,"val":"admin","end":""},{"old":"/api/v1/admin/categories/show","type":0,"val":"categories","end":""},{"old":"/api/v1/admin/categories/show","type":0,"val":"show","end":""}],
    types: placeholder as Registry['admin.categories.show']['types'],
  },
  'admin.categories.create': {
    methods: ["POST"],
    pattern: '/api/v1/admin/categories/create',
    tokens: [{"old":"/api/v1/admin/categories/create","type":0,"val":"api","end":""},{"old":"/api/v1/admin/categories/create","type":0,"val":"v1","end":""},{"old":"/api/v1/admin/categories/create","type":0,"val":"admin","end":""},{"old":"/api/v1/admin/categories/create","type":0,"val":"categories","end":""},{"old":"/api/v1/admin/categories/create","type":0,"val":"create","end":""}],
    types: placeholder as Registry['admin.categories.create']['types'],
  },
  'admin.categories.update': {
    methods: ["POST"],
    pattern: '/api/v1/admin/categories/update',
    tokens: [{"old":"/api/v1/admin/categories/update","type":0,"val":"api","end":""},{"old":"/api/v1/admin/categories/update","type":0,"val":"v1","end":""},{"old":"/api/v1/admin/categories/update","type":0,"val":"admin","end":""},{"old":"/api/v1/admin/categories/update","type":0,"val":"categories","end":""},{"old":"/api/v1/admin/categories/update","type":0,"val":"update","end":""}],
    types: placeholder as Registry['admin.categories.update']['types'],
  },
  'admin.categories.delete': {
    methods: ["POST"],
    pattern: '/api/v1/admin/categories/delete',
    tokens: [{"old":"/api/v1/admin/categories/delete","type":0,"val":"api","end":""},{"old":"/api/v1/admin/categories/delete","type":0,"val":"v1","end":""},{"old":"/api/v1/admin/categories/delete","type":0,"val":"admin","end":""},{"old":"/api/v1/admin/categories/delete","type":0,"val":"categories","end":""},{"old":"/api/v1/admin/categories/delete","type":0,"val":"delete","end":""}],
    types: placeholder as Registry['admin.categories.delete']['types'],
  },
  'admin.depense_categories.search': {
    methods: ["POST"],
    pattern: '/api/v1/admin/depense-categories/search',
    tokens: [{"old":"/api/v1/admin/depense-categories/search","type":0,"val":"api","end":""},{"old":"/api/v1/admin/depense-categories/search","type":0,"val":"v1","end":""},{"old":"/api/v1/admin/depense-categories/search","type":0,"val":"admin","end":""},{"old":"/api/v1/admin/depense-categories/search","type":0,"val":"depense-categories","end":""},{"old":"/api/v1/admin/depense-categories/search","type":0,"val":"search","end":""}],
    types: placeholder as Registry['admin.depense_categories.search']['types'],
  },
  'admin.depense_categories.show': {
    methods: ["POST"],
    pattern: '/api/v1/admin/depense-categories/show',
    tokens: [{"old":"/api/v1/admin/depense-categories/show","type":0,"val":"api","end":""},{"old":"/api/v1/admin/depense-categories/show","type":0,"val":"v1","end":""},{"old":"/api/v1/admin/depense-categories/show","type":0,"val":"admin","end":""},{"old":"/api/v1/admin/depense-categories/show","type":0,"val":"depense-categories","end":""},{"old":"/api/v1/admin/depense-categories/show","type":0,"val":"show","end":""}],
    types: placeholder as Registry['admin.depense_categories.show']['types'],
  },
  'admin.depense_categories.create': {
    methods: ["POST"],
    pattern: '/api/v1/admin/depense-categories/create',
    tokens: [{"old":"/api/v1/admin/depense-categories/create","type":0,"val":"api","end":""},{"old":"/api/v1/admin/depense-categories/create","type":0,"val":"v1","end":""},{"old":"/api/v1/admin/depense-categories/create","type":0,"val":"admin","end":""},{"old":"/api/v1/admin/depense-categories/create","type":0,"val":"depense-categories","end":""},{"old":"/api/v1/admin/depense-categories/create","type":0,"val":"create","end":""}],
    types: placeholder as Registry['admin.depense_categories.create']['types'],
  },
  'admin.depense_categories.update': {
    methods: ["POST"],
    pattern: '/api/v1/admin/depense-categories/update',
    tokens: [{"old":"/api/v1/admin/depense-categories/update","type":0,"val":"api","end":""},{"old":"/api/v1/admin/depense-categories/update","type":0,"val":"v1","end":""},{"old":"/api/v1/admin/depense-categories/update","type":0,"val":"admin","end":""},{"old":"/api/v1/admin/depense-categories/update","type":0,"val":"depense-categories","end":""},{"old":"/api/v1/admin/depense-categories/update","type":0,"val":"update","end":""}],
    types: placeholder as Registry['admin.depense_categories.update']['types'],
  },
  'admin.depense_categories.delete': {
    methods: ["POST"],
    pattern: '/api/v1/admin/depense-categories/delete',
    tokens: [{"old":"/api/v1/admin/depense-categories/delete","type":0,"val":"api","end":""},{"old":"/api/v1/admin/depense-categories/delete","type":0,"val":"v1","end":""},{"old":"/api/v1/admin/depense-categories/delete","type":0,"val":"admin","end":""},{"old":"/api/v1/admin/depense-categories/delete","type":0,"val":"depense-categories","end":""},{"old":"/api/v1/admin/depense-categories/delete","type":0,"val":"delete","end":""}],
    types: placeholder as Registry['admin.depense_categories.delete']['types'],
  },
  'clients.clients.search': {
    methods: ["POST"],
    pattern: '/api/v1/clients/search',
    tokens: [{"old":"/api/v1/clients/search","type":0,"val":"api","end":""},{"old":"/api/v1/clients/search","type":0,"val":"v1","end":""},{"old":"/api/v1/clients/search","type":0,"val":"clients","end":""},{"old":"/api/v1/clients/search","type":0,"val":"search","end":""}],
    types: placeholder as Registry['clients.clients.search']['types'],
  },
  'clients.clients.show': {
    methods: ["POST"],
    pattern: '/api/v1/clients/show',
    tokens: [{"old":"/api/v1/clients/show","type":0,"val":"api","end":""},{"old":"/api/v1/clients/show","type":0,"val":"v1","end":""},{"old":"/api/v1/clients/show","type":0,"val":"clients","end":""},{"old":"/api/v1/clients/show","type":0,"val":"show","end":""}],
    types: placeholder as Registry['clients.clients.show']['types'],
  },
  'clients.clients.create': {
    methods: ["POST"],
    pattern: '/api/v1/clients/create',
    tokens: [{"old":"/api/v1/clients/create","type":0,"val":"api","end":""},{"old":"/api/v1/clients/create","type":0,"val":"v1","end":""},{"old":"/api/v1/clients/create","type":0,"val":"clients","end":""},{"old":"/api/v1/clients/create","type":0,"val":"create","end":""}],
    types: placeholder as Registry['clients.clients.create']['types'],
  },
  'clients.clients.update': {
    methods: ["POST"],
    pattern: '/api/v1/clients/update',
    tokens: [{"old":"/api/v1/clients/update","type":0,"val":"api","end":""},{"old":"/api/v1/clients/update","type":0,"val":"v1","end":""},{"old":"/api/v1/clients/update","type":0,"val":"clients","end":""},{"old":"/api/v1/clients/update","type":0,"val":"update","end":""}],
    types: placeholder as Registry['clients.clients.update']['types'],
  },
  'clients.clients.deactivate': {
    methods: ["POST"],
    pattern: '/api/v1/clients/deactivate',
    tokens: [{"old":"/api/v1/clients/deactivate","type":0,"val":"api","end":""},{"old":"/api/v1/clients/deactivate","type":0,"val":"v1","end":""},{"old":"/api/v1/clients/deactivate","type":0,"val":"clients","end":""},{"old":"/api/v1/clients/deactivate","type":0,"val":"deactivate","end":""}],
    types: placeholder as Registry['clients.clients.deactivate']['types'],
  },
  'clients.clients.ventes': {
    methods: ["POST"],
    pattern: '/api/v1/clients/ventes',
    tokens: [{"old":"/api/v1/clients/ventes","type":0,"val":"api","end":""},{"old":"/api/v1/clients/ventes","type":0,"val":"v1","end":""},{"old":"/api/v1/clients/ventes","type":0,"val":"clients","end":""},{"old":"/api/v1/clients/ventes","type":0,"val":"ventes","end":""}],
    types: placeholder as Registry['clients.clients.ventes']['types'],
  },
  'clients.clients.solde': {
    methods: ["POST"],
    pattern: '/api/v1/clients/solde',
    tokens: [{"old":"/api/v1/clients/solde","type":0,"val":"api","end":""},{"old":"/api/v1/clients/solde","type":0,"val":"v1","end":""},{"old":"/api/v1/clients/solde","type":0,"val":"clients","end":""},{"old":"/api/v1/clients/solde","type":0,"val":"solde","end":""}],
    types: placeholder as Registry['clients.clients.solde']['types'],
  },
  'fournisseurs.fournisseurs.search': {
    methods: ["POST"],
    pattern: '/api/v1/fournisseurs/search',
    tokens: [{"old":"/api/v1/fournisseurs/search","type":0,"val":"api","end":""},{"old":"/api/v1/fournisseurs/search","type":0,"val":"v1","end":""},{"old":"/api/v1/fournisseurs/search","type":0,"val":"fournisseurs","end":""},{"old":"/api/v1/fournisseurs/search","type":0,"val":"search","end":""}],
    types: placeholder as Registry['fournisseurs.fournisseurs.search']['types'],
  },
  'fournisseurs.fournisseurs.show': {
    methods: ["POST"],
    pattern: '/api/v1/fournisseurs/show',
    tokens: [{"old":"/api/v1/fournisseurs/show","type":0,"val":"api","end":""},{"old":"/api/v1/fournisseurs/show","type":0,"val":"v1","end":""},{"old":"/api/v1/fournisseurs/show","type":0,"val":"fournisseurs","end":""},{"old":"/api/v1/fournisseurs/show","type":0,"val":"show","end":""}],
    types: placeholder as Registry['fournisseurs.fournisseurs.show']['types'],
  },
  'fournisseurs.fournisseurs.create': {
    methods: ["POST"],
    pattern: '/api/v1/fournisseurs/create',
    tokens: [{"old":"/api/v1/fournisseurs/create","type":0,"val":"api","end":""},{"old":"/api/v1/fournisseurs/create","type":0,"val":"v1","end":""},{"old":"/api/v1/fournisseurs/create","type":0,"val":"fournisseurs","end":""},{"old":"/api/v1/fournisseurs/create","type":0,"val":"create","end":""}],
    types: placeholder as Registry['fournisseurs.fournisseurs.create']['types'],
  },
  'fournisseurs.fournisseurs.update': {
    methods: ["POST"],
    pattern: '/api/v1/fournisseurs/update',
    tokens: [{"old":"/api/v1/fournisseurs/update","type":0,"val":"api","end":""},{"old":"/api/v1/fournisseurs/update","type":0,"val":"v1","end":""},{"old":"/api/v1/fournisseurs/update","type":0,"val":"fournisseurs","end":""},{"old":"/api/v1/fournisseurs/update","type":0,"val":"update","end":""}],
    types: placeholder as Registry['fournisseurs.fournisseurs.update']['types'],
  },
  'fournisseurs.fournisseurs.deactivate': {
    methods: ["POST"],
    pattern: '/api/v1/fournisseurs/deactivate',
    tokens: [{"old":"/api/v1/fournisseurs/deactivate","type":0,"val":"api","end":""},{"old":"/api/v1/fournisseurs/deactivate","type":0,"val":"v1","end":""},{"old":"/api/v1/fournisseurs/deactivate","type":0,"val":"fournisseurs","end":""},{"old":"/api/v1/fournisseurs/deactivate","type":0,"val":"deactivate","end":""}],
    types: placeholder as Registry['fournisseurs.fournisseurs.deactivate']['types'],
  },
  'fournisseurs.fournisseurs.achats': {
    methods: ["POST"],
    pattern: '/api/v1/fournisseurs/achats',
    tokens: [{"old":"/api/v1/fournisseurs/achats","type":0,"val":"api","end":""},{"old":"/api/v1/fournisseurs/achats","type":0,"val":"v1","end":""},{"old":"/api/v1/fournisseurs/achats","type":0,"val":"fournisseurs","end":""},{"old":"/api/v1/fournisseurs/achats","type":0,"val":"achats","end":""}],
    types: placeholder as Registry['fournisseurs.fournisseurs.achats']['types'],
  },
  'categories.categories.search': {
    methods: ["POST"],
    pattern: '/api/v1/categories/search',
    tokens: [{"old":"/api/v1/categories/search","type":0,"val":"api","end":""},{"old":"/api/v1/categories/search","type":0,"val":"v1","end":""},{"old":"/api/v1/categories/search","type":0,"val":"categories","end":""},{"old":"/api/v1/categories/search","type":0,"val":"search","end":""}],
    types: placeholder as Registry['categories.categories.search']['types'],
  },
  'categories.categories.show': {
    methods: ["POST"],
    pattern: '/api/v1/categories/show',
    tokens: [{"old":"/api/v1/categories/show","type":0,"val":"api","end":""},{"old":"/api/v1/categories/show","type":0,"val":"v1","end":""},{"old":"/api/v1/categories/show","type":0,"val":"categories","end":""},{"old":"/api/v1/categories/show","type":0,"val":"show","end":""}],
    types: placeholder as Registry['categories.categories.show']['types'],
  },
  'categories.categories.create': {
    methods: ["POST"],
    pattern: '/api/v1/categories/create',
    tokens: [{"old":"/api/v1/categories/create","type":0,"val":"api","end":""},{"old":"/api/v1/categories/create","type":0,"val":"v1","end":""},{"old":"/api/v1/categories/create","type":0,"val":"categories","end":""},{"old":"/api/v1/categories/create","type":0,"val":"create","end":""}],
    types: placeholder as Registry['categories.categories.create']['types'],
  },
  'categories.categories.update': {
    methods: ["POST"],
    pattern: '/api/v1/categories/update',
    tokens: [{"old":"/api/v1/categories/update","type":0,"val":"api","end":""},{"old":"/api/v1/categories/update","type":0,"val":"v1","end":""},{"old":"/api/v1/categories/update","type":0,"val":"categories","end":""},{"old":"/api/v1/categories/update","type":0,"val":"update","end":""}],
    types: placeholder as Registry['categories.categories.update']['types'],
  },
  'categories.categories.delete': {
    methods: ["POST"],
    pattern: '/api/v1/categories/delete',
    tokens: [{"old":"/api/v1/categories/delete","type":0,"val":"api","end":""},{"old":"/api/v1/categories/delete","type":0,"val":"v1","end":""},{"old":"/api/v1/categories/delete","type":0,"val":"categories","end":""},{"old":"/api/v1/categories/delete","type":0,"val":"delete","end":""}],
    types: placeholder as Registry['categories.categories.delete']['types'],
  },
  'tva_groupes.index': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/tva-groupes',
    tokens: [{"old":"/api/v1/tva-groupes","type":0,"val":"api","end":""},{"old":"/api/v1/tva-groupes","type":0,"val":"v1","end":""},{"old":"/api/v1/tva-groupes","type":0,"val":"tva-groupes","end":""}],
    types: placeholder as Registry['tva_groupes.index']['types'],
  },
  'tva_groupes.show': {
    methods: ["POST"],
    pattern: '/api/v1/tva-groupes/show',
    tokens: [{"old":"/api/v1/tva-groupes/show","type":0,"val":"api","end":""},{"old":"/api/v1/tva-groupes/show","type":0,"val":"v1","end":""},{"old":"/api/v1/tva-groupes/show","type":0,"val":"tva-groupes","end":""},{"old":"/api/v1/tva-groupes/show","type":0,"val":"show","end":""}],
    types: placeholder as Registry['tva_groupes.show']['types'],
  },
  'produits.produits.search': {
    methods: ["POST"],
    pattern: '/api/v1/produits/search',
    tokens: [{"old":"/api/v1/produits/search","type":0,"val":"api","end":""},{"old":"/api/v1/produits/search","type":0,"val":"v1","end":""},{"old":"/api/v1/produits/search","type":0,"val":"produits","end":""},{"old":"/api/v1/produits/search","type":0,"val":"search","end":""}],
    types: placeholder as Registry['produits.produits.search']['types'],
  },
  'produits.produits.show': {
    methods: ["POST"],
    pattern: '/api/v1/produits/show',
    tokens: [{"old":"/api/v1/produits/show","type":0,"val":"api","end":""},{"old":"/api/v1/produits/show","type":0,"val":"v1","end":""},{"old":"/api/v1/produits/show","type":0,"val":"produits","end":""},{"old":"/api/v1/produits/show","type":0,"val":"show","end":""}],
    types: placeholder as Registry['produits.produits.show']['types'],
  },
  'produits.produits.create': {
    methods: ["POST"],
    pattern: '/api/v1/produits/create',
    tokens: [{"old":"/api/v1/produits/create","type":0,"val":"api","end":""},{"old":"/api/v1/produits/create","type":0,"val":"v1","end":""},{"old":"/api/v1/produits/create","type":0,"val":"produits","end":""},{"old":"/api/v1/produits/create","type":0,"val":"create","end":""}],
    types: placeholder as Registry['produits.produits.create']['types'],
  },
  'produits.produits.update': {
    methods: ["POST"],
    pattern: '/api/v1/produits/update',
    tokens: [{"old":"/api/v1/produits/update","type":0,"val":"api","end":""},{"old":"/api/v1/produits/update","type":0,"val":"v1","end":""},{"old":"/api/v1/produits/update","type":0,"val":"produits","end":""},{"old":"/api/v1/produits/update","type":0,"val":"update","end":""}],
    types: placeholder as Registry['produits.produits.update']['types'],
  },
  'produits.produits.deactivate': {
    methods: ["POST"],
    pattern: '/api/v1/produits/deactivate',
    tokens: [{"old":"/api/v1/produits/deactivate","type":0,"val":"api","end":""},{"old":"/api/v1/produits/deactivate","type":0,"val":"v1","end":""},{"old":"/api/v1/produits/deactivate","type":0,"val":"produits","end":""},{"old":"/api/v1/produits/deactivate","type":0,"val":"deactivate","end":""}],
    types: placeholder as Registry['produits.produits.deactivate']['types'],
  },
  'produits.produits.alertes': {
    methods: ["POST"],
    pattern: '/api/v1/produits/alertes',
    tokens: [{"old":"/api/v1/produits/alertes","type":0,"val":"api","end":""},{"old":"/api/v1/produits/alertes","type":0,"val":"v1","end":""},{"old":"/api/v1/produits/alertes","type":0,"val":"produits","end":""},{"old":"/api/v1/produits/alertes","type":0,"val":"alertes","end":""}],
    types: placeholder as Registry['produits.produits.alertes']['types'],
  },
  'produits.produits.ajustement': {
    methods: ["POST"],
    pattern: '/api/v1/produits/ajustement',
    tokens: [{"old":"/api/v1/produits/ajustement","type":0,"val":"api","end":""},{"old":"/api/v1/produits/ajustement","type":0,"val":"v1","end":""},{"old":"/api/v1/produits/ajustement","type":0,"val":"produits","end":""},{"old":"/api/v1/produits/ajustement","type":0,"val":"ajustement","end":""}],
    types: placeholder as Registry['produits.produits.ajustement']['types'],
  },
  'produits.produits.calcul_prix': {
    methods: ["POST"],
    pattern: '/api/v1/produits/calcul-prix',
    tokens: [{"old":"/api/v1/produits/calcul-prix","type":0,"val":"api","end":""},{"old":"/api/v1/produits/calcul-prix","type":0,"val":"v1","end":""},{"old":"/api/v1/produits/calcul-prix","type":0,"val":"produits","end":""},{"old":"/api/v1/produits/calcul-prix","type":0,"val":"calcul-prix","end":""}],
    types: placeholder as Registry['produits.produits.calcul_prix']['types'],
  },
  'ventes.search': {
    methods: ["POST"],
    pattern: '/api/v1/ventes/search',
    tokens: [{"old":"/api/v1/ventes/search","type":0,"val":"api","end":""},{"old":"/api/v1/ventes/search","type":0,"val":"v1","end":""},{"old":"/api/v1/ventes/search","type":0,"val":"ventes","end":""},{"old":"/api/v1/ventes/search","type":0,"val":"search","end":""}],
    types: placeholder as Registry['ventes.search']['types'],
  },
  'ventes.get_by_criteria': {
    methods: ["POST"],
    pattern: '/api/v1/ventes/get-by-criteria',
    tokens: [{"old":"/api/v1/ventes/get-by-criteria","type":0,"val":"api","end":""},{"old":"/api/v1/ventes/get-by-criteria","type":0,"val":"v1","end":""},{"old":"/api/v1/ventes/get-by-criteria","type":0,"val":"ventes","end":""},{"old":"/api/v1/ventes/get-by-criteria","type":0,"val":"get-by-criteria","end":""}],
    types: placeholder as Registry['ventes.get_by_criteria']['types'],
  },
  'ventes.show': {
    methods: ["POST"],
    pattern: '/api/v1/ventes/show',
    tokens: [{"old":"/api/v1/ventes/show","type":0,"val":"api","end":""},{"old":"/api/v1/ventes/show","type":0,"val":"v1","end":""},{"old":"/api/v1/ventes/show","type":0,"val":"ventes","end":""},{"old":"/api/v1/ventes/show","type":0,"val":"show","end":""}],
    types: placeholder as Registry['ventes.show']['types'],
  },
  'ventes.ligne_info': {
    methods: ["POST"],
    pattern: '/api/v1/ventes/ligne-info',
    tokens: [{"old":"/api/v1/ventes/ligne-info","type":0,"val":"api","end":""},{"old":"/api/v1/ventes/ligne-info","type":0,"val":"v1","end":""},{"old":"/api/v1/ventes/ligne-info","type":0,"val":"ventes","end":""},{"old":"/api/v1/ventes/ligne-info","type":0,"val":"ligne-info","end":""}],
    types: placeholder as Registry['ventes.ligne_info']['types'],
  },
  'ventes.create': {
    methods: ["POST"],
    pattern: '/api/v1/ventes/create',
    tokens: [{"old":"/api/v1/ventes/create","type":0,"val":"api","end":""},{"old":"/api/v1/ventes/create","type":0,"val":"v1","end":""},{"old":"/api/v1/ventes/create","type":0,"val":"ventes","end":""},{"old":"/api/v1/ventes/create","type":0,"val":"create","end":""}],
    types: placeholder as Registry['ventes.create']['types'],
  },
  'ventes.update': {
    methods: ["POST"],
    pattern: '/api/v1/ventes/update',
    tokens: [{"old":"/api/v1/ventes/update","type":0,"val":"api","end":""},{"old":"/api/v1/ventes/update","type":0,"val":"v1","end":""},{"old":"/api/v1/ventes/update","type":0,"val":"ventes","end":""},{"old":"/api/v1/ventes/update","type":0,"val":"update","end":""}],
    types: placeholder as Registry['ventes.update']['types'],
  },
  'ventes.annuler': {
    methods: ["POST"],
    pattern: '/api/v1/ventes/annuler',
    tokens: [{"old":"/api/v1/ventes/annuler","type":0,"val":"api","end":""},{"old":"/api/v1/ventes/annuler","type":0,"val":"v1","end":""},{"old":"/api/v1/ventes/annuler","type":0,"val":"ventes","end":""},{"old":"/api/v1/ventes/annuler","type":0,"val":"annuler","end":""}],
    types: placeholder as Registry['ventes.annuler']['types'],
  },
  'ventes.convertir_facture': {
    methods: ["POST"],
    pattern: '/api/v1/ventes/convertir-facture',
    tokens: [{"old":"/api/v1/ventes/convertir-facture","type":0,"val":"api","end":""},{"old":"/api/v1/ventes/convertir-facture","type":0,"val":"v1","end":""},{"old":"/api/v1/ventes/convertir-facture","type":0,"val":"ventes","end":""},{"old":"/api/v1/ventes/convertir-facture","type":0,"val":"convertir-facture","end":""}],
    types: placeholder as Registry['ventes.convertir_facture']['types'],
  },
  'ventes.valider': {
    methods: ["POST"],
    pattern: '/api/v1/ventes/valider',
    tokens: [{"old":"/api/v1/ventes/valider","type":0,"val":"api","end":""},{"old":"/api/v1/ventes/valider","type":0,"val":"v1","end":""},{"old":"/api/v1/ventes/valider","type":0,"val":"ventes","end":""},{"old":"/api/v1/ventes/valider","type":0,"val":"valider","end":""}],
    types: placeholder as Registry['ventes.valider']['types'],
  },
  'ventes.delete': {
    methods: ["POST"],
    pattern: '/api/v1/ventes/delete',
    tokens: [{"old":"/api/v1/ventes/delete","type":0,"val":"api","end":""},{"old":"/api/v1/ventes/delete","type":0,"val":"v1","end":""},{"old":"/api/v1/ventes/delete","type":0,"val":"ventes","end":""},{"old":"/api/v1/ventes/delete","type":0,"val":"delete","end":""}],
    types: placeholder as Registry['ventes.delete']['types'],
  },
  'ventes.retour': {
    methods: ["POST"],
    pattern: '/api/v1/ventes/retour',
    tokens: [{"old":"/api/v1/ventes/retour","type":0,"val":"api","end":""},{"old":"/api/v1/ventes/retour","type":0,"val":"v1","end":""},{"old":"/api/v1/ventes/retour","type":0,"val":"ventes","end":""},{"old":"/api/v1/ventes/retour","type":0,"val":"retour","end":""}],
    types: placeholder as Registry['ventes.retour']['types'],
  },
  'ventes.paiement': {
    methods: ["POST"],
    pattern: '/api/v1/ventes/paiement',
    tokens: [{"old":"/api/v1/ventes/paiement","type":0,"val":"api","end":""},{"old":"/api/v1/ventes/paiement","type":0,"val":"v1","end":""},{"old":"/api/v1/ventes/paiement","type":0,"val":"ventes","end":""},{"old":"/api/v1/ventes/paiement","type":0,"val":"paiement","end":""}],
    types: placeholder as Registry['ventes.paiement']['types'],
  },
  'ventes.paiements_search': {
    methods: ["POST"],
    pattern: '/api/v1/ventes/paiements-search',
    tokens: [{"old":"/api/v1/ventes/paiements-search","type":0,"val":"api","end":""},{"old":"/api/v1/ventes/paiements-search","type":0,"val":"v1","end":""},{"old":"/api/v1/ventes/paiements-search","type":0,"val":"ventes","end":""},{"old":"/api/v1/ventes/paiements-search","type":0,"val":"paiements-search","end":""}],
    types: placeholder as Registry['ventes.paiements_search']['types'],
  },
  'ventes.document': {
    methods: ["POST"],
    pattern: '/api/v1/ventes/document',
    tokens: [{"old":"/api/v1/ventes/document","type":0,"val":"api","end":""},{"old":"/api/v1/ventes/document","type":0,"val":"v1","end":""},{"old":"/api/v1/ventes/document","type":0,"val":"ventes","end":""},{"old":"/api/v1/ventes/document","type":0,"val":"document","end":""}],
    types: placeholder as Registry['ventes.document']['types'],
  },
  'ventes.imprimer': {
    methods: ["POST"],
    pattern: '/api/v1/ventes/imprimer',
    tokens: [{"old":"/api/v1/ventes/imprimer","type":0,"val":"api","end":""},{"old":"/api/v1/ventes/imprimer","type":0,"val":"v1","end":""},{"old":"/api/v1/ventes/imprimer","type":0,"val":"ventes","end":""},{"old":"/api/v1/ventes/imprimer","type":0,"val":"imprimer","end":""}],
    types: placeholder as Registry['ventes.imprimer']['types'],
  },
  'ventes.lock': {
    methods: ["POST"],
    pattern: '/api/v1/ventes/lock',
    tokens: [{"old":"/api/v1/ventes/lock","type":0,"val":"api","end":""},{"old":"/api/v1/ventes/lock","type":0,"val":"v1","end":""},{"old":"/api/v1/ventes/lock","type":0,"val":"ventes","end":""},{"old":"/api/v1/ventes/lock","type":0,"val":"lock","end":""}],
    types: placeholder as Registry['ventes.lock']['types'],
  },
  'ventes.lock_renew': {
    methods: ["POST"],
    pattern: '/api/v1/ventes/lock-renew',
    tokens: [{"old":"/api/v1/ventes/lock-renew","type":0,"val":"api","end":""},{"old":"/api/v1/ventes/lock-renew","type":0,"val":"v1","end":""},{"old":"/api/v1/ventes/lock-renew","type":0,"val":"ventes","end":""},{"old":"/api/v1/ventes/lock-renew","type":0,"val":"lock-renew","end":""}],
    types: placeholder as Registry['ventes.lock_renew']['types'],
  },
  'ventes.unlock': {
    methods: ["POST"],
    pattern: '/api/v1/ventes/unlock',
    tokens: [{"old":"/api/v1/ventes/unlock","type":0,"val":"api","end":""},{"old":"/api/v1/ventes/unlock","type":0,"val":"v1","end":""},{"old":"/api/v1/ventes/unlock","type":0,"val":"ventes","end":""},{"old":"/api/v1/ventes/unlock","type":0,"val":"unlock","end":""}],
    types: placeholder as Registry['ventes.unlock']['types'],
  },
  'reglements.client.create': {
    methods: ["POST"],
    pattern: '/api/v1/reglements/client/create',
    tokens: [{"old":"/api/v1/reglements/client/create","type":0,"val":"api","end":""},{"old":"/api/v1/reglements/client/create","type":0,"val":"v1","end":""},{"old":"/api/v1/reglements/client/create","type":0,"val":"reglements","end":""},{"old":"/api/v1/reglements/client/create","type":0,"val":"client","end":""},{"old":"/api/v1/reglements/client/create","type":0,"val":"create","end":""}],
    types: placeholder as Registry['reglements.client.create']['types'],
  },
  'reglements.client.search': {
    methods: ["POST"],
    pattern: '/api/v1/reglements/client/search',
    tokens: [{"old":"/api/v1/reglements/client/search","type":0,"val":"api","end":""},{"old":"/api/v1/reglements/client/search","type":0,"val":"v1","end":""},{"old":"/api/v1/reglements/client/search","type":0,"val":"reglements","end":""},{"old":"/api/v1/reglements/client/search","type":0,"val":"client","end":""},{"old":"/api/v1/reglements/client/search","type":0,"val":"search","end":""}],
    types: placeholder as Registry['reglements.client.search']['types'],
  },
  'reglements.client.show': {
    methods: ["POST"],
    pattern: '/api/v1/reglements/client/show',
    tokens: [{"old":"/api/v1/reglements/client/show","type":0,"val":"api","end":""},{"old":"/api/v1/reglements/client/show","type":0,"val":"v1","end":""},{"old":"/api/v1/reglements/client/show","type":0,"val":"reglements","end":""},{"old":"/api/v1/reglements/client/show","type":0,"val":"client","end":""},{"old":"/api/v1/reglements/client/show","type":0,"val":"show","end":""}],
    types: placeholder as Registry['reglements.client.show']['types'],
  },
  'reglements.fournisseur.create': {
    methods: ["POST"],
    pattern: '/api/v1/reglements/fournisseur/create',
    tokens: [{"old":"/api/v1/reglements/fournisseur/create","type":0,"val":"api","end":""},{"old":"/api/v1/reglements/fournisseur/create","type":0,"val":"v1","end":""},{"old":"/api/v1/reglements/fournisseur/create","type":0,"val":"reglements","end":""},{"old":"/api/v1/reglements/fournisseur/create","type":0,"val":"fournisseur","end":""},{"old":"/api/v1/reglements/fournisseur/create","type":0,"val":"create","end":""}],
    types: placeholder as Registry['reglements.fournisseur.create']['types'],
  },
  'reglements.fournisseur.search': {
    methods: ["POST"],
    pattern: '/api/v1/reglements/fournisseur/search',
    tokens: [{"old":"/api/v1/reglements/fournisseur/search","type":0,"val":"api","end":""},{"old":"/api/v1/reglements/fournisseur/search","type":0,"val":"v1","end":""},{"old":"/api/v1/reglements/fournisseur/search","type":0,"val":"reglements","end":""},{"old":"/api/v1/reglements/fournisseur/search","type":0,"val":"fournisseur","end":""},{"old":"/api/v1/reglements/fournisseur/search","type":0,"val":"search","end":""}],
    types: placeholder as Registry['reglements.fournisseur.search']['types'],
  },
  'reglements.fournisseur.show': {
    methods: ["POST"],
    pattern: '/api/v1/reglements/fournisseur/show',
    tokens: [{"old":"/api/v1/reglements/fournisseur/show","type":0,"val":"api","end":""},{"old":"/api/v1/reglements/fournisseur/show","type":0,"val":"v1","end":""},{"old":"/api/v1/reglements/fournisseur/show","type":0,"val":"reglements","end":""},{"old":"/api/v1/reglements/fournisseur/show","type":0,"val":"fournisseur","end":""},{"old":"/api/v1/reglements/fournisseur/show","type":0,"val":"show","end":""}],
    types: placeholder as Registry['reglements.fournisseur.show']['types'],
  },
  'achats.search': {
    methods: ["POST"],
    pattern: '/api/v1/achats/search',
    tokens: [{"old":"/api/v1/achats/search","type":0,"val":"api","end":""},{"old":"/api/v1/achats/search","type":0,"val":"v1","end":""},{"old":"/api/v1/achats/search","type":0,"val":"achats","end":""},{"old":"/api/v1/achats/search","type":0,"val":"search","end":""}],
    types: placeholder as Registry['achats.search']['types'],
  },
  'achats.get_by_criteria': {
    methods: ["POST"],
    pattern: '/api/v1/achats/get-by-criteria',
    tokens: [{"old":"/api/v1/achats/get-by-criteria","type":0,"val":"api","end":""},{"old":"/api/v1/achats/get-by-criteria","type":0,"val":"v1","end":""},{"old":"/api/v1/achats/get-by-criteria","type":0,"val":"achats","end":""},{"old":"/api/v1/achats/get-by-criteria","type":0,"val":"get-by-criteria","end":""}],
    types: placeholder as Registry['achats.get_by_criteria']['types'],
  },
  'achats.show': {
    methods: ["POST"],
    pattern: '/api/v1/achats/show',
    tokens: [{"old":"/api/v1/achats/show","type":0,"val":"api","end":""},{"old":"/api/v1/achats/show","type":0,"val":"v1","end":""},{"old":"/api/v1/achats/show","type":0,"val":"achats","end":""},{"old":"/api/v1/achats/show","type":0,"val":"show","end":""}],
    types: placeholder as Registry['achats.show']['types'],
  },
  'achats.ligne_info': {
    methods: ["POST"],
    pattern: '/api/v1/achats/ligne-info',
    tokens: [{"old":"/api/v1/achats/ligne-info","type":0,"val":"api","end":""},{"old":"/api/v1/achats/ligne-info","type":0,"val":"v1","end":""},{"old":"/api/v1/achats/ligne-info","type":0,"val":"achats","end":""},{"old":"/api/v1/achats/ligne-info","type":0,"val":"ligne-info","end":""}],
    types: placeholder as Registry['achats.ligne_info']['types'],
  },
  'achats.create': {
    methods: ["POST"],
    pattern: '/api/v1/achats/create',
    tokens: [{"old":"/api/v1/achats/create","type":0,"val":"api","end":""},{"old":"/api/v1/achats/create","type":0,"val":"v1","end":""},{"old":"/api/v1/achats/create","type":0,"val":"achats","end":""},{"old":"/api/v1/achats/create","type":0,"val":"create","end":""}],
    types: placeholder as Registry['achats.create']['types'],
  },
  'achats.update': {
    methods: ["POST"],
    pattern: '/api/v1/achats/update',
    tokens: [{"old":"/api/v1/achats/update","type":0,"val":"api","end":""},{"old":"/api/v1/achats/update","type":0,"val":"v1","end":""},{"old":"/api/v1/achats/update","type":0,"val":"achats","end":""},{"old":"/api/v1/achats/update","type":0,"val":"update","end":""}],
    types: placeholder as Registry['achats.update']['types'],
  },
  'achats.annuler': {
    methods: ["POST"],
    pattern: '/api/v1/achats/annuler',
    tokens: [{"old":"/api/v1/achats/annuler","type":0,"val":"api","end":""},{"old":"/api/v1/achats/annuler","type":0,"val":"v1","end":""},{"old":"/api/v1/achats/annuler","type":0,"val":"achats","end":""},{"old":"/api/v1/achats/annuler","type":0,"val":"annuler","end":""}],
    types: placeholder as Registry['achats.annuler']['types'],
  },
  'achats.recevoir': {
    methods: ["POST"],
    pattern: '/api/v1/achats/recevoir',
    tokens: [{"old":"/api/v1/achats/recevoir","type":0,"val":"api","end":""},{"old":"/api/v1/achats/recevoir","type":0,"val":"v1","end":""},{"old":"/api/v1/achats/recevoir","type":0,"val":"achats","end":""},{"old":"/api/v1/achats/recevoir","type":0,"val":"recevoir","end":""}],
    types: placeholder as Registry['achats.recevoir']['types'],
  },
  'achats.retour': {
    methods: ["POST"],
    pattern: '/api/v1/achats/retour',
    tokens: [{"old":"/api/v1/achats/retour","type":0,"val":"api","end":""},{"old":"/api/v1/achats/retour","type":0,"val":"v1","end":""},{"old":"/api/v1/achats/retour","type":0,"val":"achats","end":""},{"old":"/api/v1/achats/retour","type":0,"val":"retour","end":""}],
    types: placeholder as Registry['achats.retour']['types'],
  },
  'achats.paiement': {
    methods: ["POST"],
    pattern: '/api/v1/achats/paiement',
    tokens: [{"old":"/api/v1/achats/paiement","type":0,"val":"api","end":""},{"old":"/api/v1/achats/paiement","type":0,"val":"v1","end":""},{"old":"/api/v1/achats/paiement","type":0,"val":"achats","end":""},{"old":"/api/v1/achats/paiement","type":0,"val":"paiement","end":""}],
    types: placeholder as Registry['achats.paiement']['types'],
  },
  'caisse.solde': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/caisse/solde',
    tokens: [{"old":"/api/v1/caisse/solde","type":0,"val":"api","end":""},{"old":"/api/v1/caisse/solde","type":0,"val":"v1","end":""},{"old":"/api/v1/caisse/solde","type":0,"val":"caisse","end":""},{"old":"/api/v1/caisse/solde","type":0,"val":"solde","end":""}],
    types: placeholder as Registry['caisse.solde']['types'],
  },
  'caisse.mouvements.search': {
    methods: ["POST"],
    pattern: '/api/v1/caisse/mouvements/search',
    tokens: [{"old":"/api/v1/caisse/mouvements/search","type":0,"val":"api","end":""},{"old":"/api/v1/caisse/mouvements/search","type":0,"val":"v1","end":""},{"old":"/api/v1/caisse/mouvements/search","type":0,"val":"caisse","end":""},{"old":"/api/v1/caisse/mouvements/search","type":0,"val":"mouvements","end":""},{"old":"/api/v1/caisse/mouvements/search","type":0,"val":"search","end":""}],
    types: placeholder as Registry['caisse.mouvements.search']['types'],
  },
  'caisse.get_by_criteria': {
    methods: ["POST"],
    pattern: '/api/v1/caisse/get-by-criteria',
    tokens: [{"old":"/api/v1/caisse/get-by-criteria","type":0,"val":"api","end":""},{"old":"/api/v1/caisse/get-by-criteria","type":0,"val":"v1","end":""},{"old":"/api/v1/caisse/get-by-criteria","type":0,"val":"caisse","end":""},{"old":"/api/v1/caisse/get-by-criteria","type":0,"val":"get-by-criteria","end":""}],
    types: placeholder as Registry['caisse.get_by_criteria']['types'],
  },
  'caisse.mouvements.show': {
    methods: ["POST"],
    pattern: '/api/v1/caisse/mouvements/show',
    tokens: [{"old":"/api/v1/caisse/mouvements/show","type":0,"val":"api","end":""},{"old":"/api/v1/caisse/mouvements/show","type":0,"val":"v1","end":""},{"old":"/api/v1/caisse/mouvements/show","type":0,"val":"caisse","end":""},{"old":"/api/v1/caisse/mouvements/show","type":0,"val":"mouvements","end":""},{"old":"/api/v1/caisse/mouvements/show","type":0,"val":"show","end":""}],
    types: placeholder as Registry['caisse.mouvements.show']['types'],
  },
  'caisse.ouverture': {
    methods: ["POST"],
    pattern: '/api/v1/caisse/ouverture',
    tokens: [{"old":"/api/v1/caisse/ouverture","type":0,"val":"api","end":""},{"old":"/api/v1/caisse/ouverture","type":0,"val":"v1","end":""},{"old":"/api/v1/caisse/ouverture","type":0,"val":"caisse","end":""},{"old":"/api/v1/caisse/ouverture","type":0,"val":"ouverture","end":""}],
    types: placeholder as Registry['caisse.ouverture']['types'],
  },
  'caisse.fermeture': {
    methods: ["POST"],
    pattern: '/api/v1/caisse/fermeture',
    tokens: [{"old":"/api/v1/caisse/fermeture","type":0,"val":"api","end":""},{"old":"/api/v1/caisse/fermeture","type":0,"val":"v1","end":""},{"old":"/api/v1/caisse/fermeture","type":0,"val":"caisse","end":""},{"old":"/api/v1/caisse/fermeture","type":0,"val":"fermeture","end":""}],
    types: placeholder as Registry['caisse.fermeture']['types'],
  },
  'caisse.session': {
    methods: ["POST"],
    pattern: '/api/v1/caisse/session',
    tokens: [{"old":"/api/v1/caisse/session","type":0,"val":"api","end":""},{"old":"/api/v1/caisse/session","type":0,"val":"v1","end":""},{"old":"/api/v1/caisse/session","type":0,"val":"caisse","end":""},{"old":"/api/v1/caisse/session","type":0,"val":"session","end":""}],
    types: placeholder as Registry['caisse.session']['types'],
  },
  'caisse.sessions.search': {
    methods: ["POST"],
    pattern: '/api/v1/caisse/sessions/search',
    tokens: [{"old":"/api/v1/caisse/sessions/search","type":0,"val":"api","end":""},{"old":"/api/v1/caisse/sessions/search","type":0,"val":"v1","end":""},{"old":"/api/v1/caisse/sessions/search","type":0,"val":"caisse","end":""},{"old":"/api/v1/caisse/sessions/search","type":0,"val":"sessions","end":""},{"old":"/api/v1/caisse/sessions/search","type":0,"val":"search","end":""}],
    types: placeholder as Registry['caisse.sessions.search']['types'],
  },
  'caisse.sessions.get_by_criteria': {
    methods: ["POST"],
    pattern: '/api/v1/caisse/sessions/get-by-criteria',
    tokens: [{"old":"/api/v1/caisse/sessions/get-by-criteria","type":0,"val":"api","end":""},{"old":"/api/v1/caisse/sessions/get-by-criteria","type":0,"val":"v1","end":""},{"old":"/api/v1/caisse/sessions/get-by-criteria","type":0,"val":"caisse","end":""},{"old":"/api/v1/caisse/sessions/get-by-criteria","type":0,"val":"sessions","end":""},{"old":"/api/v1/caisse/sessions/get-by-criteria","type":0,"val":"get-by-criteria","end":""}],
    types: placeholder as Registry['caisse.sessions.get_by_criteria']['types'],
  },
  'caisse.sessions.show': {
    methods: ["POST"],
    pattern: '/api/v1/caisse/sessions/show',
    tokens: [{"old":"/api/v1/caisse/sessions/show","type":0,"val":"api","end":""},{"old":"/api/v1/caisse/sessions/show","type":0,"val":"v1","end":""},{"old":"/api/v1/caisse/sessions/show","type":0,"val":"caisse","end":""},{"old":"/api/v1/caisse/sessions/show","type":0,"val":"sessions","end":""},{"old":"/api/v1/caisse/sessions/show","type":0,"val":"show","end":""}],
    types: placeholder as Registry['caisse.sessions.show']['types'],
  },
  'depense_categories.index': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/depense-categories',
    tokens: [{"old":"/api/v1/depense-categories","type":0,"val":"api","end":""},{"old":"/api/v1/depense-categories","type":0,"val":"v1","end":""},{"old":"/api/v1/depense-categories","type":0,"val":"depense-categories","end":""}],
    types: placeholder as Registry['depense_categories.index']['types'],
  },
  'depenses.search': {
    methods: ["POST"],
    pattern: '/api/v1/depenses/search',
    tokens: [{"old":"/api/v1/depenses/search","type":0,"val":"api","end":""},{"old":"/api/v1/depenses/search","type":0,"val":"v1","end":""},{"old":"/api/v1/depenses/search","type":0,"val":"depenses","end":""},{"old":"/api/v1/depenses/search","type":0,"val":"search","end":""}],
    types: placeholder as Registry['depenses.search']['types'],
  },
  'depenses.show': {
    methods: ["POST"],
    pattern: '/api/v1/depenses/show',
    tokens: [{"old":"/api/v1/depenses/show","type":0,"val":"api","end":""},{"old":"/api/v1/depenses/show","type":0,"val":"v1","end":""},{"old":"/api/v1/depenses/show","type":0,"val":"depenses","end":""},{"old":"/api/v1/depenses/show","type":0,"val":"show","end":""}],
    types: placeholder as Registry['depenses.show']['types'],
  },
  'depenses.create': {
    methods: ["POST"],
    pattern: '/api/v1/depenses/create',
    tokens: [{"old":"/api/v1/depenses/create","type":0,"val":"api","end":""},{"old":"/api/v1/depenses/create","type":0,"val":"v1","end":""},{"old":"/api/v1/depenses/create","type":0,"val":"depenses","end":""},{"old":"/api/v1/depenses/create","type":0,"val":"create","end":""}],
    types: placeholder as Registry['depenses.create']['types'],
  },
  'depenses.update': {
    methods: ["POST"],
    pattern: '/api/v1/depenses/update',
    tokens: [{"old":"/api/v1/depenses/update","type":0,"val":"api","end":""},{"old":"/api/v1/depenses/update","type":0,"val":"v1","end":""},{"old":"/api/v1/depenses/update","type":0,"val":"depenses","end":""},{"old":"/api/v1/depenses/update","type":0,"val":"update","end":""}],
    types: placeholder as Registry['depenses.update']['types'],
  },
  'depenses.delete': {
    methods: ["POST"],
    pattern: '/api/v1/depenses/delete',
    tokens: [{"old":"/api/v1/depenses/delete","type":0,"val":"api","end":""},{"old":"/api/v1/depenses/delete","type":0,"val":"v1","end":""},{"old":"/api/v1/depenses/delete","type":0,"val":"depenses","end":""},{"old":"/api/v1/depenses/delete","type":0,"val":"delete","end":""}],
    types: placeholder as Registry['depenses.delete']['types'],
  },
  'stock.search': {
    methods: ["POST"],
    pattern: '/api/v1/stock/search',
    tokens: [{"old":"/api/v1/stock/search","type":0,"val":"api","end":""},{"old":"/api/v1/stock/search","type":0,"val":"v1","end":""},{"old":"/api/v1/stock/search","type":0,"val":"stock","end":""},{"old":"/api/v1/stock/search","type":0,"val":"search","end":""}],
    types: placeholder as Registry['stock.search']['types'],
  },
  'stock.mouvements.search': {
    methods: ["POST"],
    pattern: '/api/v1/stock/mouvements/search',
    tokens: [{"old":"/api/v1/stock/mouvements/search","type":0,"val":"api","end":""},{"old":"/api/v1/stock/mouvements/search","type":0,"val":"v1","end":""},{"old":"/api/v1/stock/mouvements/search","type":0,"val":"stock","end":""},{"old":"/api/v1/stock/mouvements/search","type":0,"val":"mouvements","end":""},{"old":"/api/v1/stock/mouvements/search","type":0,"val":"search","end":""}],
    types: placeholder as Registry['stock.mouvements.search']['types'],
  },
  'stock.valorisation': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/stock/valorisation',
    tokens: [{"old":"/api/v1/stock/valorisation","type":0,"val":"api","end":""},{"old":"/api/v1/stock/valorisation","type":0,"val":"v1","end":""},{"old":"/api/v1/stock/valorisation","type":0,"val":"stock","end":""},{"old":"/api/v1/stock/valorisation","type":0,"val":"valorisation","end":""}],
    types: placeholder as Registry['stock.valorisation']['types'],
  },
  'stock.alertes': {
    methods: ["POST"],
    pattern: '/api/v1/stock/alertes',
    tokens: [{"old":"/api/v1/stock/alertes","type":0,"val":"api","end":""},{"old":"/api/v1/stock/alertes","type":0,"val":"v1","end":""},{"old":"/api/v1/stock/alertes","type":0,"val":"stock","end":""},{"old":"/api/v1/stock/alertes","type":0,"val":"alertes","end":""}],
    types: placeholder as Registry['stock.alertes']['types'],
  },
  'rapports.caisse': {
    methods: ["POST"],
    pattern: '/api/v1/rapports/caisse',
    tokens: [{"old":"/api/v1/rapports/caisse","type":0,"val":"api","end":""},{"old":"/api/v1/rapports/caisse","type":0,"val":"v1","end":""},{"old":"/api/v1/rapports/caisse","type":0,"val":"rapports","end":""},{"old":"/api/v1/rapports/caisse","type":0,"val":"caisse","end":""}],
    types: placeholder as Registry['rapports.caisse']['types'],
  },
  'rapports.stock_actuel': {
    methods: ["POST"],
    pattern: '/api/v1/rapports/stock-actuel',
    tokens: [{"old":"/api/v1/rapports/stock-actuel","type":0,"val":"api","end":""},{"old":"/api/v1/rapports/stock-actuel","type":0,"val":"v1","end":""},{"old":"/api/v1/rapports/stock-actuel","type":0,"val":"rapports","end":""},{"old":"/api/v1/rapports/stock-actuel","type":0,"val":"stock-actuel","end":""}],
    types: placeholder as Registry['rapports.stock_actuel']['types'],
  },
  'rapports.valeur_stock': {
    methods: ["POST"],
    pattern: '/api/v1/rapports/valeur-stock',
    tokens: [{"old":"/api/v1/rapports/valeur-stock","type":0,"val":"api","end":""},{"old":"/api/v1/rapports/valeur-stock","type":0,"val":"v1","end":""},{"old":"/api/v1/rapports/valeur-stock","type":0,"val":"rapports","end":""},{"old":"/api/v1/rapports/valeur-stock","type":0,"val":"valeur-stock","end":""}],
    types: placeholder as Registry['rapports.valeur_stock']['types'],
  },
  'rapports.balance_clients': {
    methods: ["POST"],
    pattern: '/api/v1/rapports/balance-clients',
    tokens: [{"old":"/api/v1/rapports/balance-clients","type":0,"val":"api","end":""},{"old":"/api/v1/rapports/balance-clients","type":0,"val":"v1","end":""},{"old":"/api/v1/rapports/balance-clients","type":0,"val":"rapports","end":""},{"old":"/api/v1/rapports/balance-clients","type":0,"val":"balance-clients","end":""}],
    types: placeholder as Registry['rapports.balance_clients']['types'],
  },
  'rapports.releve_client': {
    methods: ["POST"],
    pattern: '/api/v1/rapports/releve-client',
    tokens: [{"old":"/api/v1/rapports/releve-client","type":0,"val":"api","end":""},{"old":"/api/v1/rapports/releve-client","type":0,"val":"v1","end":""},{"old":"/api/v1/rapports/releve-client","type":0,"val":"rapports","end":""},{"old":"/api/v1/rapports/releve-client","type":0,"val":"releve-client","end":""}],
    types: placeholder as Registry['rapports.releve_client']['types'],
  },
} as const satisfies Record<string, AdonisEndpoint>

export { routes }

export const registry = {
  routes,
  $tree: {} as ApiDefinition,
}

declare module '@tuyau/core/types' {
  export interface UserRegistry {
    routes: typeof routes
    $tree: ApiDefinition
  }
}
